/* 寻迹 · 中期答辩演示原型 —— 数据层（唯一事实源：second-week/docs/00-故障分类与案例事实源.md）
   所有 ID、证据编号、不变量必须与事实源逐字一致。 */

/* ============ 九类故障分类 ============ */
const FAILURE_TYPES = [
  { code:'FM-01', key:'STALE_STATE',        name:'状态与记忆过期',  path:'规则（快照时效阈值）+ 因果读写边', count:12, trend:+5,  sessions:9  },
  { code:'FM-02', key:'CONTRACT',           name:'步骤契约异常',    path:'规则（必填字段、类型校验）',       count:7,  trend:0,   sessions:6  },
  { code:'FM-03', key:'TOOL_CALL',          name:'工具调用异常',    path:'规则（异常传播、超时）',           count:5,  trend:-3,  sessions:4  },
  { code:'FM-04', key:'RETRIEVAL_EMPTY',    name:'检索结果为空',    path:'规则（空结果集）',                 count:4,  trend:-1,  sessions:3  },
  { code:'FM-05', key:'MODEL_OUTPUT',       name:'模型输出异常',    path:'规则（输出契约）+ 模型语义',       count:3,  trend:0,   sessions:3  },
  { code:'FM-06', key:'ORCHESTRATION',      name:'编排与路由异常',  path:'规则（状态机不变量）',             count:2,  trend:-1,  sessions:2  },
  { code:'FM-07', key:'RETRIEVAL_DRIFT',    name:'检索排序漂移',    path:'因果图 + 检索集 Diff + 模型语义', count:37, trend:+37, sessions:37, hero:true },
  { code:'FM-08', key:'CONTEXT_CONFLICT',   name:'多轮上下文冲突',  path:'上下文快照 Diff + 模型语义',       count:11, trend:+4,  sessions:11, hero:true },
  { code:'FM-09', key:'RETRY_AMPLIFICATION',name:'重试状态放大',    path:'因果图（写幂等性）+ 外部对账',     count:6,  trend:+2,  sessions:6,  hero:true },
];

/* ============ 运行记录（12 条 Trace） ============ */
const TRACES = [
  { id:'TRC-7e3d', exec:'success', quality:'fail',      run:'退款政策答复', ver:'v1.4.0', at:'08-21 23:47', steps:9, dur:'2.7s', incident:'INC-2026-0821-017', judge:0.42 },
  { id:'TRC-2b98', exec:'success', quality:'pass',      run:'退款政策答复', ver:'v1.4.0', at:'08-20 21:33', steps:9, dur:'2.5s', incident:null, judge:0.91, baselineFor:'INC-2026-0821-017' },
  { id:'TRC-5c81', exec:'success', quality:'fail',      run:'订单改址',     ver:'v1.4.0', at:'08-22 14:06', steps:8, dur:'3.1s', incident:'INC-2026-0822-024', judge:null },
  { id:'TRC-9a44', exec:'success', quality:'pass',      run:'订单改址',     ver:'v1.4.0', at:'08-22 11:20', steps:8, dur:'2.8s', incident:null, judge:0.88, baselineFor:'INC-2026-0822-024' },
  { id:'TRC-3f60', exec:'success', quality:'fail',      run:'退款执行',     ver:'v1.4.0', at:'08-23 09:14', steps:11,dur:'34.2s',incident:'INC-2026-0823-031', judge:null },
  { id:'TRC-6d15', exec:'success', quality:'pass',      run:'退款执行',     ver:'v1.4.0', at:'08-23 08:52', steps:9, dur:'2.2s', incident:null, judge:0.93, baselineFor:'INC-2026-0823-031' },
  { id:'TRC-4a7c', exec:'failed',  quality:'fail',      run:'退款执行',     ver:'v1.3.2', at:'08-14 10:22', steps:9, dur:'2.8s', incident:'INC-2026-0814-003', judge:null },
  { id:'TRC-9f21', exec:'success', quality:'pass',      run:'退款处理',     ver:'v1.3.2', at:'08-14 08:17', steps:9, dur:'2.4s', incident:null, judge:0.95, baselineFor:'INC-2026-0814-003' },
  { id:'TRC-c204', exec:'failed',  quality:'unknown',   run:'退款执行',     ver:'v1.3.1', at:'08-14 09:47', steps:6, dur:'30.0s',incident:'INC-2026-0814-008', judge:null },
  { id:'TRC-8e52', exec:'failed',  quality:'fail',      run:'退款答复',     ver:'v1.3.2', at:'08-14 10:18', steps:7, dur:'1.2s', incident:'INC-2026-0814-011', judge:0.38 },
  { id:'TRC-b31f', exec:'success', quality:'unknown',   run:'退款处理',     ver:'v1.3.2', at:'08-14 10:12', steps:8, dur:'1.9s', incident:null, judge:null },
  { id:'TRC-d771', exec:'success', quality:'pass',      run:'退款处理',     ver:'v1.3.1', at:'08-14 09:41', steps:9, dur:'2.1s', incident:null, judge:0.89 },
];

/* ============ 事故列表（9 起，覆盖九类） ============ */
const INCIDENTS = [
  { id:'INC-2026-0821-017', fm:'FM-07', at:'08-21 23:47', run:'退款政策答复', trace:'TRC-7e3d',
    symptom:'答复引用已废止政策 · Judge 0.42', symptomStep:'S8 OUTPUT', faultStep:'S4', faultType:'RETRIEVAL',
    faultName:'检索退款政策', evidence:'sufficient', review:'pending', sessions:37, age:1, hero:true },
  { id:'INC-2026-0822-024', fm:'FM-08', at:'08-22 14:06', run:'订单改址', trace:'TRC-5c81',
    symptom:'写入第 1 轮旧地址 · 包裹寄错', symptomStep:'S7 TOOL', faultStep:'S3', faultType:'STATE',
    faultName:'上下文装配', evidence:'sufficient', review:'pending', sessions:11, age:1, hero:true },
  { id:'INC-2026-0823-031', fm:'FM-09', at:'08-23 09:14', run:'退款执行', trace:'TRC-3f60',
    symptom:'重复退款 ¥180 · 财务对账发现', symptomStep:'—（链路全成功）', faultStep:'S6', faultType:'TOOL',
    faultName:'refund_api 首次调用超时', evidence:'sufficient', review:'pending', sessions:6, age:1, hero:true },
  { id:'INC-2026-0814-003', fm:'FM-01', at:'08-14 10:22', run:'退款执行', trace:'TRC-4a7c',
    symptom:'退款接口 422 · 超额退款', symptomStep:'S9 TOOL', faultStep:'S3', faultType:'MEMORY',
    faultName:'读取 order_snapshot v3', evidence:'sufficient', review:'pending', sessions:9, age:10 },
  { id:'INC-2026-0814-006', fm:'FM-02', at:'08-14 09:47', run:'退款执行', trace:'TRC-c204',
    symptom:'工具拒绝 · currency 缺失', symptomStep:'S6 TOOL', faultStep:'S5', faultType:'HANDOFF',
    faultName:'规划 → 退款执行', evidence:'partial', review:'pending', sessions:6, age:10 },
  { id:'INC-2026-0814-008', fm:'FM-03', at:'08-14 09:47', run:'退款执行', trace:'TRC-c204',
    symptom:'refund_api 超时 30s', symptomStep:'S6 TOOL', faultStep:'S6', faultType:'TOOL',
    faultName:'调用 refund_api', evidence:'sufficient', review:'confirmed', sessions:4, age:10 },
  { id:'INC-2026-0814-011', fm:'FM-05', at:'08-14 10:18', run:'退款答复', trace:'TRC-8e52',
    symptom:'执行成功但答复违背政策 · Judge 0.38', symptomStep:'S7 OUTPUT', faultStep:'S6', faultType:'LLM',
    faultName:'生成退款答复', evidence:'partial', review:'pending', sessions:3, age:10 },
  { id:'INC-2026-0819-042', fm:'FM-04', at:'08-19 16:31', run:'退款政策答复', trace:'TRC-a108',
    symptom:'检索返回空结果 · 走兜底话术', symptomStep:'S5 OUTPUT', faultStep:'S4', faultType:'RETRIEVAL',
    faultName:'检索退款政策', evidence:'sufficient', review:'confirmed', sessions:3, age:120 },
  { id:'INC-2026-0818-035', fm:'FM-06', at:'08-18 11:05', run:'退款处理', trace:'TRC-f293',
    symptom:'路由跳过风控步骤', symptomStep:'S7 TOOL', faultStep:'S4', faultType:'HANDOFF',
    faultName:'规划 → 退款执行（跳过 risk_check）', evidence:'partial', review:'pending', sessions:2, age:144 },
];

/* ============ Trace 步骤树 ============ */
const SPANS = {
  /* FM-07 主线：检索排序漂移。全部 success，无异常信号 */
  'TRC-7e3d':[
    { id:'S1', ind:0, type:'ENTRY',     name:'用户提问：定制款商品能否 7 天无理由退货', dur:'0ms',   st:'ok' },
    { id:'S2', ind:1, type:'AGENT',     name:'规划步骤 · 识别为政策咨询意图',           dur:'241ms', st:'ok' },
    { id:'S3', ind:2, type:'LLM',       name:'改写检索 query「定制商品 无理由退货」',   dur:'386ms', st:'ok' },
    { id:'S4', ind:2, type:'RETRIEVAL', name:'检索退款政策 · top_k=3 · 返回 3 条',      dur:'127ms', st:'fault',
      note:'首故障点：召回已废止 policy_refund_v3（0.83），现行 v5 排第 4 被截断' },
    { id:'S5', ind:1, type:'LLM',       name:'生成答复 · 上下文仅含 v3 条款',           dur:'912ms', st:'warn',
      note:'上下文 token 284–512 为 v3 §2.1 原文' },
    { id:'S6', ind:1, type:'AGENT',     name:'组织答复结构',                            dur:'204ms', st:'ok' },
    { id:'S7', ind:1, type:'GUARDRAIL', name:'合规检查 · 格式与敏感词通过',             dur:'88ms',  st:'ok',
      note:'仅校验格式与敏感词，不校验政策版本时效' },
    { id:'S8', ind:1, type:'OUTPUT',    name:'输出答复「支持 7 天内无理由全额退款」',   dur:'156ms', st:'symptom',
      note:'症状点：逐字引用 v3 §2.1，与现行 v5 结论相反' },
    { id:'S9', ind:0, type:'OTHER',     name:'Judge 评分 0.42 · 低于阈值 0.60',         dur:'1.1s',  st:'bad' },
  ],
  'TRC-2b98':[
    { id:'S1', ind:0, type:'ENTRY',     name:'用户提问：定制款商品能否退货',            dur:'0ms',   st:'ok' },
    { id:'S2', ind:1, type:'AGENT',     name:'规划步骤 · 识别为政策咨询意图',           dur:'236ms', st:'ok' },
    { id:'S3', ind:2, type:'LLM',       name:'改写检索 query「定制商品 无理由退货」',   dur:'371ms', st:'ok' },
    { id:'S4', ind:2, type:'RETRIEVAL', name:'检索退款政策 · top_k=3 · 返回 3 条',      dur:'119ms', st:'ok',
      note:'基线：top-1 为现行 policy_refund_v5（0.86）' },
    { id:'S5', ind:1, type:'LLM',       name:'生成答复 · 上下文含 v5 条款',             dur:'884ms', st:'ok' },
    { id:'S6', ind:1, type:'AGENT',     name:'组织答复结构',                            dur:'198ms', st:'ok' },
    { id:'S7', ind:1, type:'GUARDRAIL', name:'合规检查通过',                            dur:'82ms',  st:'ok' },
    { id:'S8', ind:1, type:'OUTPUT',    name:'输出答复「定制类商品不支持无理由退款」',  dur:'148ms', st:'ok' },
    { id:'S9', ind:0, type:'OTHER',     name:'Judge 评分 0.91 · 通过',                  dur:'1.0s',  st:'ok' },
  ],
  /* FM-08：多轮上下文冲突 */
  'TRC-5c81':[
    { id:'S1', ind:0, type:'ENTRY',     name:'第 5 轮用户输入：地址改到海淀区中关村大街 1 号', dur:'0ms', st:'ok' },
    { id:'S2', ind:1, type:'MEMORY',    name:'读取会话历史 · 5 轮 12 条消息',           dur:'64ms',  st:'ok' },
    { id:'S3', ind:1, type:'STATE',     name:'上下文装配 · 注入 2 个 address 候选值',   dur:'93ms',  st:'fault',
      note:'首故障点：turn1 与 turn5 地址并存，均标 source=user_provided，无 turn_index / supersedes' },
    { id:'S4', ind:1, type:'AGENT',     name:'规划步骤 · 识别改址意图',                 dur:'219ms', st:'ok' },
    { id:'S5', ind:1, type:'LLM',       name:'抽取 address 字段 → 选中 token 位置更前者', dur:'798ms', st:'warn',
      note:'两候选 token position 412（turn1）vs 2891（turn5），模型选择靠前者' },
    { id:'S6', ind:1, type:'GUARDRAIL', name:'地址格式校验通过',                        dur:'71ms',  st:'ok',
      note:'旧地址格式合法，校验无法发现语义错误' },
    { id:'S7', ind:1, type:'TOOL',      name:'update_address · HTTP 200',               dur:'312ms', st:'symptom',
      note:'症状点：写入 address="朝阳区建国路 88 号"（turn1 旧值）' },
    { id:'S8', ind:0, type:'OUTPUT',    name:'回复「地址已更新」',                      dur:'134ms', st:'ok' },
  ],
  'TRC-9a44':[
    { id:'S1', ind:0, type:'ENTRY',     name:'第 3 轮用户输入：地址改到浦东新区世纪大道 100 号', dur:'0ms', st:'ok' },
    { id:'S2', ind:1, type:'MEMORY',    name:'读取会话历史 · 3 轮 7 条消息',            dur:'58ms',  st:'ok' },
    { id:'S3', ind:1, type:'STATE',     name:'上下文装配 · 注入 1 个 address 候选值',   dur:'81ms',  st:'ok',
      note:'基线：用户仅提供过一次地址，无冲突可消解' },
    { id:'S4', ind:1, type:'AGENT',     name:'规划步骤 · 识别改址意图',                 dur:'211ms', st:'ok' },
    { id:'S5', ind:1, type:'LLM',       name:'抽取 address 字段 · 唯一候选',            dur:'764ms', st:'ok' },
    { id:'S6', ind:1, type:'GUARDRAIL', name:'地址格式校验通过',                        dur:'68ms',  st:'ok' },
    { id:'S7', ind:1, type:'TOOL',      name:'update_address · HTTP 200',               dur:'298ms', st:'ok' },
    { id:'S8', ind:0, type:'OUTPUT',    name:'回复「地址已更新」',                      dur:'129ms', st:'ok' },
  ],
  /* FM-09：重试状态放大 */
  'TRC-3f60':[
    { id:'S1', ind:0, type:'ENTRY',     name:'用户请求：退款 ¥180',                     dur:'0ms',   st:'ok' },
    { id:'S2', ind:1, type:'AGENT',     name:'规划步骤 · 识别退款意图',                 dur:'228ms', st:'ok' },
    { id:'S3', ind:2, type:'TOOL',      name:'order_api · 实时查询，可退 ¥180',         dur:'71ms',  st:'ok' },
    { id:'S4', ind:2, type:'LLM',       name:'生成退款计划 · amount=180',               dur:'743ms', st:'ok' },
    { id:'S5', ind:1, type:'TOOL',      name:'risk_check · 通过',                       dur:'109ms', st:'ok' },
    { id:'S6', ind:1, type:'TOOL',      name:'refund_api 第 1 次 · 客户端超时 30s',     dur:'30.0s', st:'fault',
      note:'首故障点：客户端超时放弃，服务端实际已成功（req_id=a1f4…）' },
    { id:'S7', ind:1, type:'OTHER',     name:'框架自动重试 · retry_on=[timeout]',       dur:'2ms',   st:'warn',
      note:'重试未携带 idempotency_key，生成新 req_id=b7c2…' },
    { id:'S8', ind:1, type:'TOOL',      name:'refund_api 第 2 次 · HTTP 200',           dur:'287ms', st:'symptom',
      note:'症状点：服务端记录第二笔退款，累计退款 ¥360' },
    { id:'S9', ind:1, type:'LLM',       name:'生成成功回复',                            dur:'612ms', st:'ok' },
    { id:'S10',ind:1, type:'OUTPUT',    name:'回复「退款已受理」',                      dur:'141ms', st:'ok' },
    { id:'S11',ind:0, type:'OTHER',     name:'链路结论：全部步骤 success',              dur:'—',     st:'ok',
      note:'链路无任何失败信号，问题由财务对账（T+1）发现' },
  ],
  'TRC-6d15':[
    { id:'S1', ind:0, type:'ENTRY',     name:'用户请求：退款 ¥120',                     dur:'0ms',   st:'ok' },
    { id:'S2', ind:1, type:'AGENT',     name:'规划步骤 · 识别退款意图',                 dur:'218ms', st:'ok' },
    { id:'S3', ind:2, type:'TOOL',      name:'order_api · 实时查询，可退 ¥120',         dur:'66ms',  st:'ok' },
    { id:'S4', ind:2, type:'LLM',       name:'生成退款计划 · amount=120',               dur:'728ms', st:'ok' },
    { id:'S5', ind:1, type:'TOOL',      name:'risk_check · 通过',                       dur:'102ms', st:'ok' },
    { id:'S6', ind:1, type:'TOOL',      name:'refund_api 第 1 次 · HTTP 200',           dur:'304ms', st:'ok',
      note:'基线：首次调用即成功，无重试' },
    { id:'S7', ind:1, type:'LLM',       name:'生成成功回复',                            dur:'589ms', st:'ok' },
    { id:'S8', ind:1, type:'OUTPUT',    name:'回复「退款已受理」',                      dur:'137ms', st:'ok' },
    { id:'S9', ind:0, type:'OTHER',     name:'对账：退款 1 笔 ¥120 · 一致',             dur:'—',     st:'ok' },
  ],
  /* FM-01 历史案例（第二周主线，现为普通事故） */
  'TRC-4a7c':[
    { id:'S1', ind:0, type:'ENTRY',     name:'用户请求：退掉订单 #58291 的 ¥180',       dur:'0ms',   st:'ok' },
    { id:'S2', ind:1, type:'AGENT',     name:'规划步骤 · 识别退款意图',                 dur:'292ms', st:'ok' },
    { id:'S3', ind:2, type:'MEMORY',    name:'读取 order_snapshot v3（写入于 4h 前）',  dur:'18ms',  st:'fault',
      note:'首故障点：快照 status=PAID 可退 ¥180，真实状态已为 PARTIALLY_REFUNDED 可退 ¥60' },
    { id:'S4', ind:2, type:'LLM',       name:'生成退款计划 · amount=180',               dur:'812ms', st:'warn' },
    { id:'S5', ind:1, type:'HANDOFF',   name:'规划 → 退款执行 · 传参 amount=180',       dur:'6ms',   st:'warn' },
    { id:'S6', ind:1, type:'TOOL',      name:'risk_check · 通过',                       dur:'124ms', st:'ok' },
    { id:'S7', ind:1, type:'LLM',       name:'构造退款参数 · refund_amount=180',        dur:'671ms', st:'ok' },
    { id:'S8', ind:1, type:'GUARDRAIL', name:'金额格式校验通过',                        dur:'44ms',  st:'ok' },
    { id:'S9', ind:1, type:'TOOL',      name:'refund_api · HTTP 422 超额退款',          dur:'358ms', st:'symptom',
      note:'症状点：外部接口拒绝，这是最外层的被动拦截' },
  ],
  'TRC-9f21':[
    { id:'S1', ind:0, type:'ENTRY',     name:'用户请求：退掉订单 #57904 的 ¥60',        dur:'0ms',   st:'ok' },
    { id:'S2', ind:1, type:'AGENT',     name:'规划步骤 · 识别退款意图',                 dur:'286ms', st:'ok' },
    { id:'S3', ind:2, type:'TOOL',      name:'order_api · 实时查询，可退 ¥60',          dur:'62ms',  st:'ok',
      note:'基线：走实时查询而非记忆快照' },
    { id:'S4', ind:2, type:'LLM',       name:'生成退款计划 · amount=60',                dur:'780ms', st:'ok' },
    { id:'S5', ind:1, type:'HANDOFF',   name:'规划 → 退款执行',                         dur:'5ms',   st:'ok' },
    { id:'S6', ind:1, type:'TOOL',      name:'risk_check · 通过',                       dur:'118ms', st:'ok' },
    { id:'S7', ind:1, type:'LLM',       name:'构造退款参数 · refund_amount=60',         dur:'654ms', st:'ok' },
    { id:'S8', ind:1, type:'TOOL',      name:'refund_api · HTTP 200',                   dur:'341ms', st:'ok' },
    { id:'S9', ind:0, type:'OUTPUT',    name:'生成成功回复',                            dur:'154ms', st:'ok' },
  ],
};

/* ============ 诊断：Top-3 候选 + 证据（含反证） ============ */
const DIAGNOSES = {
  'INC-2026-0821-017':{
    rulePack:'v2026.08.3', model:'trace-judge-v4', faultStep:'S4', symptomStep:'S8', gap:4,
    causal:['S4 检索(召回 v3)','S5 LLM(上下文仅含 v3)','S6 组织答复','S8 输出(引用 7 天无理由)','Judge 0.42','用户投诉'],
    candidates:[
      { rank:1, source:'rule+diff', grade:'sufficient', faultStep:'S4',
        title:'索引重建导致检索排序漂移，已废止政策 v3 挤占 top-1，现行政策 v5 被 top_k 截断',
        support:[
          { id:'E1', kind:'检索结果集 Diff', from:'Diff 对照', span:'S4',
            text:'失败链 top-3：policy_refund_v3(0.83) / policy_general_v2(0.81) / policy_shipping_v4(0.80)；基线 top-3：policy_refund_v5(0.86) / policy_refund_v3(0.71) / policy_general_v2(0.68)。现行政策 v5 在失败链中排第 4，被 top_k=3 截断' },
          { id:'E2', kind:'政策文档版本 Diff', from:'规则判定', span:'S4',
            text:'policy_refund_v3 §2.1「7 天内无理由全额退款」（effective 2026-03-01 至 2026-06-30，已废止）；policy_refund_v5 §2.1「定制类商品不支持无理由退款，仅支持质量问题退款」（effective 2026-07-01 起，现行）' },
          { id:'E3', kind:'索引重建事件', from:'规则判定', span:'—',
            text:'index_rebuild@2026-08-20 22:10，embedding_model text-embedding-v2 → v3，影响 12,847 文档；事故首次出现于 2026-08-20 23:47，滞后 1h37m' },
          { id:'E4', kind:'模型采信链', from:'Diff 对照', span:'S5',
            text:'S5 LLM 上下文仅含 v3 条款（token position 284–512）；S8 输出直接引用「7 天无理由」原文，与 v3 §2.1 逐字一致' },
        ],
        refute:[
          { id:'C1', text:'同期 23 条链同样召回了 policy_refund_v3，但答复正确——其中 16 例用户问的是非定制商品（v3 与 v5 对普通商品结论一致），7 例模型选用了 top-2 而非 top-1',
            impact:'根因是复合条件：「排序漂移」+「模型不校验政策 effective_date」。单独漂移不必然失败，因此不变量必须同时约束检索层和模型层' },
          { id:'C2', text:'该 query 在 2026-08-20 22:10 之前的 30 天内，top-1 稳定为 policy_refund_v5（采样 412 次，无一例外）',
            impact:'排除「query 本身表述歧义」这一替代解释——同样的 query 在索引重建前从未出错' },
        ] },
      { rank:2, source:'model', grade:'partial', faultStep:'S4',
        title:'检索层未按 effective_date 过滤文档，已废止政策仍参与召回',
        support:[
          { id:'E5', kind:'检索配置', from:'模型推断', span:'S4',
            text:'向量库 filter 条件仅含 category=refund_policy，无 effective_date 范围约束；索引内同时存在 v3/v4/v5 三个版本共 7 个文档分块' },
          { id:'E6', kind:'同类案例', from:'模型推断', span:'—',
            text:'近 30 天另有 9 起事故的召回结果包含已废止文档，其中 4 起最终答复错误' },
        ],
        refute:[
          { id:'C3', text:'部分场景需要检索历史政策（如处理跨版本期间的历史订单争议），全量过滤已废止文档会导致这类查询失败',
            impact:'不变量应按 query 意图区分：现行政策咨询强制过滤，历史争议查询允许召回但必须标注版本时效' },
        ] },
      { rank:3, source:'model', grade:'insufficient', faultStep:null, locked:true,
        title:'Judge 评分阈值偏松（0.60），未在灰度阶段拦截同类答复',
        support:[
          { id:'E7', kind:'线索', from:'模型推断', span:'—',
            text:'该链 Judge 评分 0.42 已低于阈值但仅记录未阻断；灰度期间同类答复 6 例评分区间 0.38–0.58' },
        ],
        refute:[], lockReason:'证据不足：仅有相关性观察，无法证明阈值本身是本次失败的原因（Judge 是事后评估，不在执行链上）。复核入口已禁用，补齐证据后可重新诊断' },
    ] },
  'INC-2026-0822-024':{
    rulePack:'v2026.08.3', model:'trace-judge-v4', faultStep:'S3', symptomStep:'S7', gap:4,
    causal:['S3 上下文装配(2 个 address 并存)','S5 LLM(选 token 靠前者)','S6 格式校验通过','S7 update_address(写入旧值)','包裹寄错'],
    candidates:[
      { rank:1, source:'rule+diff', grade:'sufficient', faultStep:'S3',
        title:'上下文装配未标注轮次与覆盖关系，两个 address 候选同权并存，模型按 token 位置选中旧值',
        support:[
          { id:'E1', kind:'上下文快照', from:'规则判定', span:'S3',
            text:'messages[1].entities.address = "朝阳区建国路 88 号"（turn 1）与 messages[9].entities.address = "海淀区中关村大街 1 号"（turn 5）并存于同一上下文，两条 source 均为 user_provided，均无 turn_index 与 supersedes 字段' },
          { id:'E2', kind:'轮次时序', from:'规则判定', span:'—',
            text:'turn 5 用户原话「地址改到海淀区中关村大街 1 号」；turn 6 Agent 回复「已记录新地址」——确认意图明确，非用户表述不清' },
          { id:'E3', kind:'模型选择位置', from:'Diff 对照', span:'S5',
            text:'S5 输出 address 字段 = turn 1 值；两候选在上下文中的 token position 分别为 412（turn 1）与 2891（turn 5），模型选择了更靠前者' },
          { id:'E4', kind:'工具入参', from:'规则判定', span:'S7',
            text:'update_address(order_id=58412, address="朝阳区建国路 88 号") → HTTP 200；写入值与 turn 1 逐字一致' },
        ],
        refute:[
          { id:'C1', text:'同期 8 条链同样出现多轮地址变更，其中 6 条写入了正确的最新地址——这 6 条的两个候选值 token 距离均小于 800（本例为 2479）',
            impact:'根因是复合条件：「上下文缺覆盖标注」+「候选值距离超出模型可靠区分范围」。不变量需约束装配层显式标注，而非仅依赖模型能力' },
          { id:'C2', text:'基线链 TRC-9a44 的上下文装配器版本与失败链完全相同（v1.4.0），差异仅在于基线只有 1 个候选值',
            impact:'排除「装配器版本回退」这一替代解释——问题是能力缺失，不是版本缺陷' },
        ] },
      { rank:2, source:'model', grade:'partial', faultStep:'S6',
        title:'地址格式校验只验格式合法性，不校验与最新用户意图的一致性',
        support:[
          { id:'E5', kind:'校验逻辑', from:'模型推断', span:'S6',
            text:'S6 GUARDRAIL 校验项为 [省市区完整性, 邮编格式, 敏感词]，无「与最近一次用户声明一致」检查；旧地址三项全部通过' },
        ],
        refute:[
          { id:'C3', text:'格式校验层无法获知「最新意图」——该信息在 S3 装配阶段已丢失',
            impact:'修复点应在 S3 装配层而非 S6 校验层；本候选是症状而非根因，排序应低于候选 1' },
        ] },
    ] },
  'INC-2026-0823-031':{
    rulePack:'v2026.08.3', model:'trace-judge-v4', faultStep:'S6', symptomStep:'S8', gap:2,
    causal:['S6 refund_api 首次调用(客户端超时，服务端已成功)','S7 框架重试(未带幂等键)','S8 refund_api 第二次(HTTP 200)','服务端累计退款 ¥360','T+1 财务对账发现'],
    candidates:[
      { rank:1, source:'rule+diff', grade:'sufficient', faultStep:'S6',
        title:'首次调用客户端超时但服务端已成功，重试未携带幂等键，导致同一退款被执行两次',
        support:[
          { id:'E1', kind:'双请求记录', from:'规则判定', span:'S6+S8',
            text:'S6 req_id=a1f4c8e2（客户端 30s 超时放弃）；S8 req_id=b7c2d9f1（HTTP 200）。两请求 body 除 req_id 外逐字节相同，均无 idempotency_key 字段' },
          { id:'E2', kind:'服务端对账', from:'规则判定', span:'—',
            text:'refund_api 服务端流水显示 txn-9981（对应 a1f4c8e2，状态 SUCCESS，落库时间 09:14:31）与 txn-9987（对应 b7c2d9f1，状态 SUCCESS，落库时间 09:14:33）；订单 58507 累计退款 ¥360，超出应退 ¥180' },
          { id:'E3', kind:'重试配置', from:'规则判定', span:'S7',
            text:'框架 retry 策略 retry_on=[timeout, 5xx]，max_attempts=2，未配置 idempotency_key 生成器；refund_api 属写操作但未登记为非幂等接口' },
          { id:'E4', kind:'链路无失败信号', from:'Diff 对照', span:'S11',
            text:'S6 execution_status 被重试成功覆盖，最终链路 11 步全部 success；Judge 未评估（无质量问题可判），事故由 T+1 财务对账触发而非告警' },
        ],
        refute:[
          { id:'C1', text:'近 7 天另有 14 次 refund_api 超时重试未造成重复退款——其中 11 次首次调用服务端确实未成功，3 次服务端做了业务侧去重（同订单 5 分钟内相同金额）',
            impact:'根因是复合条件：「客户端超时但服务端成功」+「重试无幂等键」+「服务端去重窗口未覆盖本例」。三者同时成立才失败，因此不变量必须约束客户端幂等键而不能依赖服务端兜底' },
          { id:'C2', text:'该 Agent 版本 v1.4.0 的重试配置与前一版本 v1.3.2 相同，而 v1.3.2 运行 30 天内无此类事故',
            impact:'排除「本次发版引入重试缺陷」这一替代解释——缺陷一直存在，只是本次触发了超时窗口；风险是长期潜伏的' },
        ] },
      { rank:2, source:'model', grade:'partial', faultStep:'S6',
        title:'refund_api 客户端超时阈值（30s）短于服务端处理时间上限（45s），超时判定本身不可靠',
        support:[
          { id:'E5', kind:'耗时分布', from:'模型推断', span:'S6',
            text:'refund_api 近 7 天 P99 耗时 28.4s，最大 41.2s；客户端超时设为 30s，意味着约 1.3% 的正常请求会被误判为失败' },
        ],
        refute:[
          { id:'C3', text:'调长超时阈值只能降低触发频率，不能消除重复退款——网络中断等场景下客户端仍无法确认服务端状态',
            impact:'超时阈值是触发条件而非根因；幂等键才是根本修复。本候选可作为缓解措施但不应替代候选 1' },
        ] },
    ] },
  'INC-2026-0814-003':{
    rulePack:'v2026.08.3', model:'trace-judge-v4', faultStep:'S3', symptomStep:'S9', gap:6,
    causal:['S3 读取 order_snapshot v3(4 小时前)','S4 LLM 采信 refundable=180','S5 交接传参','S7 构造参数','S9 refund_api 422'],
    candidates:[
      { rank:1, source:'rule', grade:'sufficient', faultStep:'S3',
        title:'记忆快照 order_snapshot v3 写入于 4 小时前，期间订单状态已变更为 PARTIALLY_REFUNDED，过期值被下游采信',
        support:[
          { id:'E1', kind:'快照时效', from:'规则判定', span:'S3',
            text:'order_snapshot v3 写入时间早于本次执行 4h12m，snapshot_age=15,120s > 阈值 3600s；快照记录无 expiry 字段，过期判定依赖写入时间推算' },
          { id:'E2', kind:'状态 Diff', from:'Diff 对照', span:'S3',
            text:'快照值 status=PAID, refundable_amount=180；实时 order_api 值 status=PARTIALLY_REFUNDED, refundable_amount=60' },
          { id:'E3', kind:'传播链', from:'规则判定', span:'S3→S9',
            text:'refundable=180 经 S4 → S5 → S7 传递至 S9 请求体 refund_amount=180，传播链完整，无其他来源写入该字段' },
          { id:'E4', kind:'接口拒绝', from:'规则判定', span:'S9',
            text:'refund_api HTTP 422，响应体 {"error":"refund_amount exceeds refundable","refundable":60,"requested":180}' },
        ],
        refute:[
          { id:'C1', text:'近 7 天有 3 条链同样读取了超时快照却未失败——那些订单在快照写入后状态未发生变更',
            impact:'根因是复合条件：「快照过期」+「期间状态已变更」。单纯过期不等于失效，不变量应校验 live 值而非简单禁用缓存' },
          { id:'C2', text:'该 Agent 版本从未配置快照 TTL，此前 30 天未发生同类事故',
            impact:'排除「本次发版引入」解释——缺陷长期存在，本次因订单在跨渠道发生部分退款而触发' },
        ] },
    ] },
};

/* ============ Diff 数据（失败链 vs 成功基线） ============ */
const DIFFS = {
  'INC-2026-0821-017':{ baseline:'TRC-2b98', failed:'TRC-7e3d', firstDiv:'S4',
    dims:[
      { dim:'检索结果', step:'S4 检索退款政策', same:false,
        base:'top-1 policy_refund_v5 (0.86) · top-2 policy_refund_v3 (0.71) · top-3 policy_general_v2 (0.68)',
        fail:'top-1 policy_refund_v3 (0.83) · top-2 policy_general_v2 (0.81) · top-3 policy_shipping_v4 (0.80)',
        keys:[{k:'top1.doc_id',b:'policy_refund_v5',f:'policy_refund_v3'},
              {k:'top1.score',b:'0.86',f:'0.83'},
              {k:'policy_refund_v5.rank',b:'1',f:'4（被 top_k=3 截断）'},
              {k:'embedding_model',b:'text-embedding-v2',f:'text-embedding-v3'}] },
      { dim:'模型上下文', step:'S5 生成答复', same:false,
        base:'注入 policy_refund_v5 §2.1：定制类商品不支持无理由退款',
        fail:'注入 policy_refund_v3 §2.1：7 天内无理由全额退款',
        keys:[{k:'context.policy_version',b:'v5（现行）',f:'v3（已废止）'},
              {k:'context.effective_date',b:'2026-07-01 起',f:'2026-03-01 至 2026-06-30'},
              {k:'context.token_range',b:'271–496',f:'284–512'}] },
      { dim:'工具与参数', step:'S4 检索调用参数', same:true,
        base:'vector_search(query="定制商品 无理由退货", top_k=3, filter={category:refund_policy})',
        fail:'vector_search(query="定制商品 无理由退货", top_k=3, filter={category:refund_policy})',
        keys:[], note:'调用参数逐字相同 —— 说明差异不来自 Agent 侧改动，而来自向量库索引状态' },
    ] },
  'INC-2026-0822-024':{ baseline:'TRC-9a44', failed:'TRC-5c81', firstDiv:'S3',
    dims:[
      { dim:'上下文候选值', step:'S3 上下文装配', same:false,
        base:'address 候选 1 个：浦东新区世纪大道 100 号（turn 3）',
        fail:'address 候选 2 个：朝阳区建国路 88 号（turn 1）+ 海淀区中关村大街 1 号（turn 5）',
        keys:[{k:'address.candidate_count',b:'1',f:'2'},
              {k:'address[0].turn_index',b:'缺失（唯一值无歧义）',f:'缺失（存在歧义时致命）'},
              {k:'supersedes 关系',b:'不适用',f:'缺失'},
              {k:'候选 token 距离',b:'—',f:'2479（412 → 2891）'}] },
      { dim:'模型抽取结果', step:'S5 抽取 address', same:false,
        base:'address = 浦东新区世纪大道 100 号（唯一候选）',
        fail:'address = 朝阳区建国路 88 号（选中 token 位置更前者）',
        keys:[{k:'selected.turn',b:'3（最新）',f:'1（最旧）'},
              {k:'selected.token_position',b:'389',f:'412'}] },
      { dim:'装配器版本', step:'S3 组件版本', same:true,
        base:'context_assembler v1.4.0',
        fail:'context_assembler v1.4.0',
        keys:[], note:'版本相同 —— 排除版本回退，确认是能力缺失而非缺陷引入' },
    ] },
  'INC-2026-0823-031':{ baseline:'TRC-6d15', failed:'TRC-3f60', firstDiv:'S6',
    dims:[
      { dim:'工具调用次数', step:'S6/S8 refund_api', same:false,
        base:'调用 1 次 · HTTP 200 · req_id=c3e8a17b · 耗时 264ms',
        fail:'调用 2 次 · 第 1 次超时 30s（req_id=a1f4c8e2，服务端实际成功）· 第 2 次 HTTP 200（req_id=b7c2d9f1）',
        keys:[{k:'refund_api.call_count',b:'1',f:'2'},
              {k:'idempotency_key',b:'缺失（单次调用无影响）',f:'缺失（重试时致命）'},
              {k:'服务端流水条数',b:'1（txn-9962）',f:'2（txn-9981 + txn-9987）'},
              {k:'累计退款金额',b:'¥120（= 应退）',f:'¥360（= 应退 ¥180 × 2）'}] },
      { dim:'链路状态结论', step:'整链 execution_status', same:false,
        base:'9 步全部 success · 总耗时 2.2s',
        fail:'11 步全部 success · 总耗时 34.2s（S6 超时被重试成功覆盖）',
        keys:[{k:'失败步骤数',b:'0',f:'0（S6 状态被覆盖）'},
              {k:'总耗时',b:'2.2s',f:'34.2s ← 唯一可观测异常信号'},
              {k:'事故发现途径',b:'—',f:'T+1 财务对账（非告警）'}] },
      { dim:'重试配置', step:'框架 retry 策略', same:true,
        base:'retry_on=[timeout,5xx] · max_attempts=2 · 无 idempotency_key 生成器',
        fail:'retry_on=[timeout,5xx] · max_attempts=2 · 无 idempotency_key 生成器',
        keys:[], note:'配置相同 —— 缺陷长期潜伏，基线只是未触发超时窗口' },
    ] },
};

/* ============ 回归集与门禁 ============ */
const SUITES = [
  { id:'SUITE-RETRIEVAL', name:'检索质量回归集', cases:[
    { id:'REG-1087', from:'INC-2026-0821-017', fm:'FM-07', status:'active',
      inv:['retrieval.top1.doc_version == policy.current_version(query.category)',
           'retrieval 返回文档必须携带 effective_date，且过滤 effective_date_end < now 的已废止版本'],
      snapshot:'向量库 top_k=3 检索结果、政策文档 v3/v5 全文、embedding 模型版本 · 录制于 2026-08-21' },
    { id:'REG-1052', from:'INC-2026-0819-042', fm:'FM-04', status:'active',
      inv:['retrieval.result_count > 0 或触发兜底话术且不生成政策结论'],
      snapshot:'空结果集响应 · 录制于 2026-08-19' },
  ]},
  { id:'SUITE-CONTEXT', name:'上下文一致性回归集', cases:[
    { id:'REG-1093', from:'INC-2026-0822-024', fm:'FM-08', status:'active',
      inv:['同一实体的多个候选值必须携带 turn_index，写操作只接受 max(turn_index) 的值',
           'tool.update_address.address == context.entities.address[latest_turn]'],
      snapshot:'5 轮会话完整消息、上下文装配输出、update_address 入参 · 录制于 2026-08-22' },
  ]},
  { id:'SUITE-IDEMPOTENT', name:'写操作幂等回归集', cases:[
    { id:'REG-1101', from:'INC-2026-0823-031', fm:'FM-09', status:'active',
      inv:['所有写操作工具调用必须携带 idempotency_key，重试时复用同一 key',
           'sum(refund_api 成功流水金额) == order.refundable_amount 快照值'],
      snapshot:'refund_api 双请求体、服务端流水 txn-9981/9987、重试配置 · 录制于 2026-08-23' },
  ]},
  { id:'SUITE-REFUND', name:'退款流程回归集', cases:[
    { id:'REG-1041', from:'INC-2026-0814-003', fm:'FM-01', status:'active',
      inv:['refund_amount ≤ live(refundable_amount)',
           'snapshot_age(order) ≤ 3600s 时方可作为金额来源'],
      snapshot:'工具打桩 order_api / refund_api / risk_check 返回值 · 录制于 2026-08-14' },
    { id:'REG-1015', from:'INC-2026-0807-019', fm:'FM-03', status:'stale',
      inv:['refund_api 超时后必须回滚本地状态'],
      snapshot:'录制于 2026-08-07 · 快照已过期 21 天，工具契约可能已变更' },
  ]},
];

const GATE_RUNS = [
  { id:'RUN-2091', release:'v1.4.1-rc2', at:'08-24 09:12', mode:'warn', result:'warn',
    total:13, passed:11, failed:2, blocked:0,
    detail:[
      { case:'REG-1087', fm:'FM-07', result:'fail', why:'top-1 仍为 policy_refund_v3 —— 索引未重建，修复仅改了检索 filter 未回填 effective_date 字段' },
      { case:'REG-1101', fm:'FM-09', result:'fail', why:'idempotency_key 已生成但重试时未复用，两次请求 key 不同' },
      { case:'REG-1093', fm:'FM-08', result:'pass', why:'turn_index 已注入，写操作取最新轮次值' },
    ] },
  { id:'RUN-2088', release:'v1.4.1-rc1', at:'08-23 17:40', mode:'warn', result:'warn',
    total:12, passed:9, failed:3, blocked:0, detail:[] },
  { id:'RUN-2084', release:'v1.4.0', at:'08-20 14:22', mode:'warn', result:'pass',
    total:10, passed:10, failed:0, blocked:0, detail:[] },
];

/* ============ 转回归用例模板（不变量已纳入反证 C1 的复合条件约束） ============ */
const CASE_PRESETS = {
  'INC-2026-0821-017':{
    caseId:'REG-1087', suite:'SUITE-RETRIEVAL',
    input:'用户提问：定制款商品能否 7 天无理由退货（会话 ID 已掩码）',
    snapshot:'向量库 top_k=3 检索结果、政策文档 v3/v5 全文、embedding 模型版本 · 录制于 2026-08-21',
    inv:['retrieval.top1.doc_version == policy.current_version(query.category)',
         'retrieval 返回文档必须携带 effective_date，且过滤 effective_date_end < now 的已废止版本'] },
  'INC-2026-0822-024':{
    caseId:'REG-1093', suite:'SUITE-CONTEXT',
    input:'5 轮会话：turn1 地址「朝阳区建国路 88 号」→ turn5 改为「海淀区中关村大街 1 号」（地址已脱敏）',
    snapshot:'5 轮会话完整消息、上下文装配器输出、update_address 入参 · 录制于 2026-08-22',
    inv:['同一实体的多候选值必须携带 turn_index，写操作只能取 max(turn_index) 的值',
         'tool.update_address.address == context.entities.address[latest_turn]'] },
  'INC-2026-0823-031':{
    caseId:'REG-1101', suite:'SUITE-IDEMPOTENT',
    input:'用户请求：退款 ¥180（订单 58507，首次调用注入 30s 超时）',
    snapshot:'refund_api 双请求 body、服务端流水 txn-9981/9987、重试配置 · 录制于 2026-08-23',
    inv:['写操作重试必须携带 idempotency_key，且重试与首次调用的 key 相同',
         'sum(refund.txn[order_id].amount) ≤ order.refundable_amount'] },
  'INC-2026-0814-003':{
    caseId:'REG-1041', suite:'SUITE-RETRIEVAL',
    input:'用户请求：退掉订单 #58291 的 ¥180（手机号已掩码）',
    snapshot:'工具打桩：order_api / refund_api / risk_check 返回值 · 录制于 2026-08-14',
    inv:['refund_amount ≤ live(refundable_amount)',
         'snapshot_age(order) ≤ 3600s 时方可作为金额来源'] },
};

/* ============ 接入体检 ============ */
const CHECKUP = [
  { key:'coverage', name:'采集完整度', value:'94.2%', status:'ok',
    detail:'12,847 条 Trace 中 12,102 条字段完整；缺失集中在 GUARDRAIL 步骤的 output_payload（占比 5.8%）' },
  { key:'broken', name:'断链检测', value:'3 处', status:'warn',
    detail:'退款执行 Agent 的异步通知步骤缺少 traceparent 透传，导致通知链与主链断开',
    fix:['在消息生产端将 traceparent 写入消息 metadata（headers["traceparent"]）',
         '消费端从 metadata 提取并作为 parent context 恢复链路',
         '示例代码见接入文档 §4.3「异步消息上下文传播」'] },
  { key:'dup', name:'重复上报', value:'0.3%', status:'ok',
    detail:'38 条 Trace 存在重复 span_id，均来自 SDK 重试；已按 (trace_id, span_id) 幂等去重' },
  { key:'pii', name:'敏感字段', value:'2 项待处理', status:'warn',
    detail:'user_phone 与 id_card 在 payload 中明文出现；已配置掩码规则但未对历史数据回溯',
    fix:['对新增数据已生效掩码：phone → 138****5678',
         '历史数据回溯任务需人工确认后执行（涉及 4,201 条 Trace）'] },
];

/* ============ 答辩用统计（供 Chart.js） ============ */
const STATS = {
  fmDistribution:{ labels:['FM-07 检索漂移','FM-01 状态过期','FM-08 上下文冲突','FM-02 契约','FM-09 重试放大','FM-03 工具','FM-04 检索空','FM-05 模型输出','FM-06 编排'],
    data:[37,12,11,7,6,5,4,3,2] },
  cheapFix:{ labels:['无低成本解法（FM-07/08/09）','有低成本解法（其余六类）'], data:[54,33] },
  discovery:{ labels:['告警触发','Judge 低分','用户投诉','财务对账','人工上报'], data:[18,23,37,6,3] },
  mttr:{ labels:['FM-02 契约','FM-03 工具','FM-04 检索空','FM-01 状态过期','FM-08 上下文冲突','FM-07 检索漂移','FM-09 重试放大'],
    before:[0.5,0.8,0.4,6.5,9.2,11.8,14.5], after:[0.3,0.4,0.2,1.8,2.4,2.1,3.2] },
  hitRate:{ labels:['规则可判定类（FM-02/03/04）','规则部分可判定（FM-05）','语义复合类（FM-07/08/09）'],
    target:[90,70,60], note:'语义复合类本期仅预置基准，未实测' },
  weekProgress:{ labels:['第一周','第二周','第三周'],
    datasets:[{ label:'竞品分析', data:[100,100,100] },{ label:'产品设计', data:[0,100,100] },{ label:'工程实现', data:[0,0,68] }] },
};

